using Database;

public class Blueprints_U57 : BlueprintProvider
{
	public override void SetupBlueprints()
	{
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_flint_ash", "bottom_gotch_flint_ash_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_petal_neonpink", "bottom_gotch_petal_neonpink_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_electro_sweetle", "bottom_gotch_electro_sweetle_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_wortseed_chromo", "bottom_gotch_wortseed_chromo_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_symbio_oakmolt", "bottom_gotch_symbio_oakmolt_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_quantum_radglo", "bottom_gotch_quantum_radglo_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_peagreen_glitch", "bottom_gotch_peagreen_glitch_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_muck_earwax", "bottom_gotch_muck_earwax_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_satsuma_resin", "bottom_gotch_satsuma_resin_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_rusty_grubby", "bottom_gotch_rusty_grubby_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_grape_alkali", "bottom_gotch_grape_alkali_kanim");
		AddClothing(ClothingType.DupeBottoms, PermitRarity.Decent, "permit_bottom_gotch_charcoal_obelus", "bottom_gotch_charcoal_obelus_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_flint_ash", "socks_gotch_flint_ash_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_petal_neonpink", "socks_gotch_petal_neonpink_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_electro_sweetle", "socks_gotch_electro_sweetle_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_wortseed_chromo", "socks_gotch_wortseed_chromo_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_symbio_oakmolt", "socks_gotch_symbio_oakmolt_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_quantum_radglo", "socks_gotch_quantum_radglo_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_peagreen_glitch", "socks_gotch_peagreen_glitch_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_muck_earwax", "socks_gotch_muck_earwax_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_satsuma_resin", "socks_gotch_satsuma_resin_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_rusty_grubby", "socks_gotch_rusty_grubby_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_grape_alkali", "socks_gotch_grape_alkali_kanim");
		AddClothing(ClothingType.DupeShoes, PermitRarity.Common, "permit_socks_gotch_charcoal_obelus", "socks_gotch_charcoal_obelus_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_flint_ash", "gloves_gotch_flint_ash_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_petal_neonpink", "gloves_gotch_petal_neonpink_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_electro_sweetle", "gloves_gotch_electro_sweetle_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_wortseed_chromo", "gloves_gotch_wortseed_chromo_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_symbio_oakmolt", "gloves_gotch_symbio_oakmolt_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_quantum_radglo", "gloves_gotch_quantum_radglo_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_peagreen_glitch", "gloves_gotch_peagreen_glitch_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_muck_earwax", "gloves_gotch_muck_earwax_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_satsuma_resin", "gloves_gotch_satsuma_resin_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_rusty_grubby", "gloves_gotch_rusty_grubby_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_grape_alkali", "gloves_gotch_grape_alkali_kanim");
		AddClothing(ClothingType.DupeGloves, PermitRarity.Common, "permit_gloves_gotch_charcoal_obelus", "gloves_gotch_charcoal_obelus_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_ennui_flint", "top_gotch_ennui_flint_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_gluon_petal", "top_gotch_gluon_petal_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_rivet_electro", "top_gotch_rivet_electro_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_basin_wortseed", "top_gotch_basin_wortseed_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_vitro_symbio", "top_gotch_vitro_symbio_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_nuked_quantum", "top_gotch_nuked_quantum_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_mush_peagreen", "top_gotch_mush_peagreen_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_flatus_muck", "top_gotch_flatus_muck_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_canker_satsuma", "top_gotch_canker_satsuma_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_puce_rusty", "top_gotch_puce_rusty_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_dusky_grape", "top_gotch_dusky_grape_kanim");
		AddClothing(ClothingType.DupeTops, PermitRarity.Decent, "permit_top_gotch_ash_charcoal", "top_gotch_ash_charcoal_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_black_hatchstone", "jetsuit_black_hatchstone_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_black_kelly", "jetsuit_black_kelly_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_black_red", "jetsuit_black_red_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_black_torpor", "jetsuit_black_torpor_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_black_ultra", "jetsuit_black_ultra_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_white_atomic", "jetsuit_white_atomic_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_white_charcoal", "jetsuit_white_charcoal_kanim");
		AddClothing(ClothingType.JetSuitBody, PermitRarity.Nifty, "permit_jetsuit_white_magenta", "jetsuit_white_magenta_kanim");
		AddClothing(ClothingType.JetSuitShoes, PermitRarity.Common, "permit_jet_shoes_basic_black", "jet_shoes_basic_black_kanim");
		AddClothing(ClothingType.JetSuitShoes, PermitRarity.Common, "permit_jet_shoes_basic_white", "jet_shoes_basic_white_kanim");
		AddClothing(ClothingType.JetSuitGloves, PermitRarity.Common, "permit_jet_gloves_obelus", "jet_gloves_obelus_kanim");
		AddClothing(ClothingType.JetSuitGloves, PermitRarity.Common, "permit_jet_gloves_gloom", "jet_gloves_gloom_kanim");
		AddClothing(ClothingType.JetSuitGloves, PermitRarity.Common, "permit_jet_gloves_orange", "jet_gloves_orange_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_torpor_obelus", "jet_helmet_00_torpor_obelus_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_charcoal_orange", "jet_helmet_00_charcoal_orange_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_magenta_obelus", "jet_helmet_00_magenta_obelus_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_red_obelus", "jet_helmet_00_red_obelus_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_atomic_gloom", "jet_helmet_00_atomic_gloom_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_kelly_obelus", "jet_helmet_00_kelly_obelus_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_hatchstone_obelus", "jet_helmet_00_hatchstone_obelus_kanim");
		AddClothing(ClothingType.JetSuitHelmet, PermitRarity.Nifty, "permit_jet_helmet_00_ultra_obelus", "jet_helmet_00_ultra_obelus_kanim");
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_001", new string[4] { "permit_jet_helmet_00_torpor_obelus", "permit_jetsuit_black_torpor", "permit_jet_gloves_obelus", "permit_jet_shoes_basic_black" });
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_002", new string[4] { "permit_jet_helmet_00_charcoal_orange", "permit_jetsuit_white_charcoal", "permit_jet_gloves_orange", "permit_jet_shoes_basic_white" });
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_003", new string[4] { "permit_jet_helmet_00_magenta_obelus", "permit_jetsuit_white_magenta", "permit_jet_gloves_obelus", "permit_jet_shoes_basic_white" });
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_004", new string[4] { "permit_jet_helmet_00_red_obelus", "permit_jetsuit_black_red", "permit_jet_gloves_obelus", "permit_jet_shoes_basic_black" });
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_005", new string[4] { "permit_jet_helmet_00_atomic_gloom", "permit_jetsuit_white_atomic", "permit_jet_gloves_gloom", "permit_jet_shoes_basic_white" });
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_006", new string[4] { "permit_jet_helmet_00_kelly_obelus", "permit_jetsuit_black_kelly", "permit_jet_gloves_obelus", "permit_jet_shoes_basic_black" });
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_007", new string[4] { "permit_jet_helmet_00_hatchstone_obelus", "permit_jetsuit_black_hatchstone", "permit_jet_gloves_obelus", "permit_jet_shoes_basic_black" });
		AddOutfit(OutfitType.JetSuit, "outfit_jetsuit_008", new string[4] { "permit_jet_helmet_00_ultra_obelus", "permit_jetsuit_black_ultra", "permit_jet_gloves_obelus", "permit_jet_shoes_basic_black" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_grey", new string[4] { "permit_top_gotch_ennui_flint", "permit_bottom_gotch_flint_ash", "permit_gloves_gotch_flint_ash", "permit_socks_gotch_flint_ash" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_pink", new string[4] { "permit_top_gotch_gluon_petal", "permit_bottom_gotch_petal_neonpink", "permit_gloves_gotch_petal_neonpink", "permit_socks_gotch_petal_neonpink" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_blue", new string[4] { "permit_top_gotch_rivet_electro", "permit_bottom_gotch_electro_sweetle", "permit_gloves_gotch_electro_sweetle", "permit_socks_gotch_electro_sweetle" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_blue_2", new string[4] { "permit_top_gotch_basin_wortseed", "permit_bottom_gotch_wortseed_chromo", "permit_gloves_gotch_wortseed_chromo", "permit_socks_gotch_wortseed_chromo" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_teal", new string[4] { "permit_top_gotch_vitro_symbio", "permit_bottom_gotch_symbio_oakmolt", "permit_gloves_gotch_symbio_oakmolt", "permit_socks_gotch_symbio_oakmolt" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_green_radioactive", new string[4] { "permit_top_gotch_nuked_quantum", "permit_bottom_gotch_quantum_radglo", "permit_gloves_gotch_quantum_radglo", "permit_socks_gotch_quantum_radglo" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_green", new string[4] { "permit_top_gotch_mush_peagreen", "permit_bottom_gotch_peagreen_glitch", "permit_gloves_gotch_peagreen_glitch", "permit_socks_gotch_peagreen_glitch" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_brown", new string[4] { "permit_top_gotch_flatus_muck", "permit_bottom_gotch_muck_earwax", "permit_gloves_gotch_muck_earwax", "permit_socks_gotch_muck_earwax" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_orange", new string[4] { "permit_top_gotch_canker_satsuma", "permit_bottom_gotch_satsuma_resin", "permit_gloves_gotch_satsuma_resin", "permit_socks_gotch_satsuma_resin" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_red", new string[4] { "permit_top_gotch_puce_rusty", "permit_bottom_gotch_rusty_grubby", "permit_gloves_gotch_rusty_grubby", "permit_socks_gotch_rusty_grubby" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_purple", new string[4] { "permit_top_gotch_dusky_grape", "permit_bottom_gotch_grape_alkali", "permit_gloves_gotch_grape_alkali", "permit_socks_gotch_grape_alkali" });
		AddOutfit(OutfitType.Clothing, "outfit_gotchies_black", new string[4] { "permit_top_gotch_ash_charcoal", "permit_bottom_gotch_charcoal_obelus", "permit_gloves_gotch_charcoal_obelus", "permit_socks_gotch_charcoal_obelus" });
		AddBuilding("ManualGenerator", PermitRarity.Nifty, "permit_generatormanual_a", "generatormanual_a_kanim");
		AddBuilding("ManualGenerator", PermitRarity.Nifty, "permit_generatormanual_b", "generatormanual_b_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_chilli_white", "walls_triangle_white_chilli_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_satsuma_white", "walls_triangle_white_satsuma_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_lemon_white", "walls_triangle_white_lemon_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_kelly_white", "walls_triangle_white_kelly_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_cobalt_white", "walls_triangle_white_cobalt_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_flamingo_white", "walls_triangle_white_flamingo_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_charcoal_white", "walls_triangle_white_charcoal_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_white_chilli", "walls_triangle_chilli_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_white_satsuma", "walls_triangle_satsuma_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_white_lemon", "walls_triangle_lemon_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_white_kelly", "walls_triangle_kelly_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_white_cobalt", "walls_triangle_cobalt_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_white_flamingo", "walls_triangle_flamingo_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_triangle_white_charcoal", "walls_triangle_charcoal_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_x_chilli_white", "walls_x_chilli_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_x_satsuma_white", "walls_x_satsuma_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_x_lemon_white", "walls_x_lemon_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_x_kelly_white", "walls_x_kelly_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_x_cobalt_white", "walls_x_cobalt_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_x_flamingo_white", "walls_x_flamingo_white_kanim");
		AddBuilding("ExteriorWall", PermitRarity.Common, "permit_walls_x_charcoal_white", "walls_x_charcoal_white_kanim");
	}
}
